### ISSUE TITLE
Pangolin exits with error if variant with wildcard character

### ISSUE THREAD

**Issue by tsivaarumugam** [tkzeng/Pangolin#26]
Hi Team,

While using a VCF file with wildcard character "*" in the allele field [Spanning-or-overlapping-deletions-allele](https://gatk.broadinstitute.org/hc/en-us/articles/360035531912-Spanning-or-overlapping-deletions-allele), Pangolin exits with error.

Example entry: 3       60539233        .       AAAATATAT       AATAT,*  550     PASS   .   .   .

Error trace:
Traceback (most recent call last):
 File "pangolin", line 8, in <module>
   sys.exit(main())
 File "python3.8/site-packages/pangolin/pangolin.py", line 250, in main
   scores = process_variant(lnum+i, str(variant.CHROM), int(variant.POS), variant.REF, str(variant.ALT[0]), gtf, models, args)
 File "python3.8/site-packages/pangolin/pangolin.py", line 130, in process_variant
   loss_neg, gain_neg = compute_score(ref_seq, alt_seq, '-', d, models)
 File "python3.8/site-packages/pangolin/pangolin.py", line 30, in compute_score
   ref_seq = one_hot_encode(ref_seq, strand).T
 File "python3.8/site-packages/pangolin/pangolin.py", line 24, in one_hot_encode
   seq = np.asarray(list(map(int, list(seq[::-1]))))
ValueError: invalid literal for int() with base 10: 'M'

**Comment by oleraj** [comment]
I have this issue as well.  It would be better if this variant could be skipped rather than exiting.
