### ISSUE TITLE
missing 1 required positional argument: 'type_code'

### ISSUE THREAD

**Issue by astulaaa** [tkzeng/Pangolin#7]
Hello, I am getting this kind of error. The input files are hg38 based, db and and reference used were the same as the ones suggested in theGoogle Colab code. My input vcf file at least visually appears to be formatted exactly the same as your example vcf.  

Using CPU
Traceback (most recent call last):
  File "anaconda3/envs/pytorch/bin/pangolin", line 8, in <module>
    sys.exit(main())
  File "anaconda3/envs/pytorch/lib/python3.10/site-packages/pangolin/pangolin.py", line 238, in main
    variants.infos["Pangolin"] = vcf.parser._Info(
TypeError: Info.__new__() missing 1 required positional argument: 'type_code'

Could you help me with this please?
Asta

**Comment by tkzeng** [comment]
Hi, 

Sorry about this, it looks like installing PyVCF with pip is broken. Could you follow the updated installation instructions on the README? Thank you!

**Comment by sermare** [comment]
You can fix it by: 

!pip install "setuptools<58" --upgrade
!pip install pyvcf gffutils biopython pandas pyfastx

**Comment by sruthisrini** [comment]
> Hi,
> 
> Sorry about this, it looks like installing PyVCF with pip is broken. Could you follow the updated installation instructions on the README? Thank you!

Hey @tkzeng,
I tried `pip install pyvcf gffutils biopython pandas pyfastx` and still the same error. Could you please help?

**Comment by kkchau** [comment]
@tkzeng if you're open to it, I've submitted a [PR](https://github.com/tkzeng/Pangolin/pull/19) to remove PyVCF from the dependencies since a) it's been basically abandoned and b) when digging into some of the bugginess, I noticed that there are actually two slightly versions of PyVCF 0.6.8 (latest)...

That PR replaces PyVCF with pysam, which should also offer much stricter VCF parsing. Running a quick test with the example VCF seems to work fine.

**Comment by geertvandeweyer** [comment]
@tkzeng  : the fix from kkchau is also incorporated in my PR [here](https://github.com/tkzeng/Pangolin/pull/33) , also avaialble as a docker
